export const PROJECTS = [
  {
    id: 'atrion',
    number: '1',
    name: 'Atrion',
    type: 'Physics Engine',
    category: 'experiments',
    description:
      'Physics-based concurrency control. Adaptive thresholds, deterministic backpressure, and priority-based load shedding.',
    link: 'https://github.com/cluster-127/atrion',
  },
  {
    id: 'mindfry',
    number: '2',
    name: 'Mindfry',
    type: 'Biological Memory',
    category: 'experiments',
    description:
      'A Subjective Biological Memory Substrate — it processes data through a cognitive layer',
    link: 'https://github.com/cluster-127/mindfry',
  },
  {
    id: 'nabu',
    number: '3',
    name: 'Nabu',
    type: 'Cognitive Substrate',
    category: 'experiments',
    description:
      'Nabu is a high-performance Cognitive Runtime, designed to instill Biological Metabolism into software systems.',
    link: 'https://github.com/cluster-127/nabu-how',
  },
  {
    id: 'tripwired',
    number: '4',
    name: 'Tripwired',
    type: 'Behavioral Control',
    category: 'experiments',
    description:
      'Tripwired monitors AI agent behavior and decides when they should stop acting — before they spiral out of control.',
    link: 'https://github.com/cluster-127/tripwired',
  },
  {
    id: 'morpheus',
    number: '5',
    name: 'Morpheus',
    type: 'Topographic Execution',
    category: 'experiments',
    description:
      'Morpheus purpose is to offer a passive space that determines where entities can exist, how much, and for how long.',
    link: 'https://github.com/cluster-127/morpheus',
  },
  {
    id: 'cognitum',
    number: '6',
    name: 'Cognitum',
    type: 'Policy Executor',
    category: 'experiments',
    description:
      'Deterministic policy gate for human and AI-generated code. Local-first SDK/API validation, CI gate, reproducible certificates.',
    link: 'https://github.com/cluster-127/cognitum',
  },

  {
    id: 'adrogue',
    number: '1',
    name: 'AdRogue',
    type: 'Ad Platform',
    category: 'products',
    description: 'Ad & Revenue Platform',
    link: 'https://adsrogue.com/',
  },
  {
    id: 'tracehound',
    number: '2',
    name: 'Tracehound',
    type: 'Security Buffer',
    category: 'products',
    description: 'Deterministic Runtime Security for Modern Applications.',
    link: '#',
  },
  {
    id: 'blackbox',
    number: '3',
    name: 'Blackbox',
    type: 'Forensic Audit Engine',
    category: 'products',
    description: 'Forensic UI Audit Engine — The Black Box Recorder for Critical Financial UIs',
    link: '#',
  },
  {
    id: 'volta',
    number: '4',
    name: 'Volta',
    type: 'Headless Platform Engine',
    category: 'products',
    description: 'Headless Platform Engine for Low-Code/No-Code Applications',
    link: '#',
  },
  {
    id: 'kairon',
    number: '5',
    name: 'Kairon',
    type: 'Bid Optimizer',
    category: 'products',
    description: 'Bid optimization runtime for paid acquisition campaigns',
    link: '#',
  },

  {
    id: 'sigil-security',
    number: '1',
    name: 'Sigil Security',
    type: 'Security Primitive',
    category: 'oss',
    description: 'A Cryptographic Primitive for the Professional Security Ecosystem.',
    link: 'https://github.com/laphilosophia/sigil-security',
  },
  {
    id: 'crypthold',
    number: '2',
    name: 'Crypthold',
    type: 'Secure Store',
    category: 'oss',
    description:
      'Secure encrypted config store for Node.js (HKDF, key rotation, lockfile concurrency, atomic writes).',
    link: 'https://github.com/laphilosophia/crypthold',
  },
  {
    id: 'strime',
    number: '3',
    name: 'Strime',
    type: 'Projection Engine',
    category: 'oss',
    description:
      'Streaming projection engine — extract fields at multi-gigabit speeds with O(1) memory',
    link: 'https://github.com/laphilosophia/strime',
  },
  {
    id: 'api-tape',
    number: '4',
    name: 'API Tape',
    type: 'Record & Replay',
    category: 'oss',
    description:
      'High-integrity HTTP proxy for deterministic API record & replay. Works everywhere.',
    link: 'https://github.com/laphilosophia/api-tape',
  },
  {
    id: 'axiom',
    number: '5',
    name: 'Axiom',
    type: 'Document Orchestrator',
    category: 'oss',
    description: 'Local-first document lifecycle management application',
    link: 'https://github.com/laphilosophia/axiom',
  },
  {
    id: 'lexicon',
    number: '6',
    name: 'Lexicon',
    type: 'Decision Engine',
    category: 'oss',
    description:
      'Technical specification and architectural decisions for the decision archaeology platform.',
    link: 'https://github.com/laphilosophia/lexicon',
  },
]
