export const PROJECTS = [
  {
    id: 'atrion',
    number: '01',
    name: 'ATRION',
    type: 'Physics Engine',
    desc: 'Digital physics for traffic orchestration.',
    tags: ['Rust', 'WASM', 'SIMD', 'Resilience'],
    link: 'https://atrion.run',
  },
  {
    id: 'mindfry',
    number: '02',
    name: 'MINDFRY',
    type: 'Memory with a Conscience',
    desc: 'Subjective biological memory substrate.',
    tags: ['Rust', 'CRD', 'Consciousness'],
    link: 'https://mindfry-docs.vercel.app/',
  },
  {
    id: 'nabu',
    number: '03',
    name: 'NABU',
    type: 'Cognitive Substrate',
    desc: 'Physics engine for synthetic cognition.',
    tags: ['TypeScript', 'Hebbian', 'Phase Graph'],
    link: 'https://github.com/cluster-127/nabu-how',
  },
  {
    id: 'tripwired',
    number: '04',
    name: 'TRIPWIRED',
    type: 'Behavioral Control Kernel',
    desc: 'Kill-Switch for autonomous agents.',
    tags: ['TypeScript', 'LLM Safety', 'Deterministic'],
    link: 'https://github.com/cluster-127/tripwired',
  },
  {
    id: 'tes',
    number: '05',
    name: 'TES',
    type: 'Topographic Execution Substrate',
    desc: 'High-performance temporal accountant & resource allocator.',
    tags: ['Rust', 'Entropy Engine', 'Spatial'],
    link: 'https://github.com/cluster-127/tes',
  },
  {
    id: 'adrogue',
    number: '06',
    name: 'ADROGUE',
    type: 'White-label Video Ad Platform',
    desc: 'Deterministic security buffer.',
    tags: ['Node.js', 'AdTech', 'Commercial'],
    link: 'https://adsrogue.com/',
  },
  {
    id: 'tracehound',
    number: '06',
    name: 'TRACEHOUND',
    type: 'Security Substrate',
    desc: 'Deterministic security buffer.',
    tags: ['Rust', 'AuditChain', 'Open-Core'],
    link: 'https://tracehound.vercel.app/',
  },
  {
    id: 'clearhold',
    number: '07',
    name: 'CLEARHOLD',
    type: 'Trust Protocol',
    desc: 'Payment-agnostic escrow orchestration.',
    tags: ['Node.js', 'FinTech', 'Commercial'],
    link: 'https://clearhold.vercel.app/',
  },
  {
    id: 'tcrtools',
    number: '08',
    name: 'TCR.TOOLS',
    type: 'Temporal Coordination Runtime',
    desc: 'Deterministic intent resolution & time-travel debugging.',
    tags: ['TypeScript', 'Undo/Redo', 'DevTools'],
    link: 'https://tcr-tools.vercel.app/',
  },
]
